/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/achievements`; params?: Router.UnknownInputParams; } | { pathname: `/create`; params?: Router.UnknownInputParams; } | { pathname: `/debug-notifications`; params?: Router.UnknownInputParams; } | { pathname: `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `/general`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mood-history`; params?: Router.UnknownInputParams; } | { pathname: `/my-quotes`; params?: Router.UnknownInputParams; } | { pathname: `/notification-center`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/reminders`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/animes`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/moods`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/name`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/permissions`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/achievements`; params?: Router.UnknownOutputParams; } | { pathname: `/create`; params?: Router.UnknownOutputParams; } | { pathname: `/debug-notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `/general`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/mood-history`; params?: Router.UnknownOutputParams; } | { pathname: `/my-quotes`; params?: Router.UnknownOutputParams; } | { pathname: `/notification-center`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/reminders`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/animes`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/moods`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/name`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/permissions`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/achievements${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `/debug-notifications${`?${string}` | `#${string}` | ''}` | `/favorites${`?${string}` | `#${string}` | ''}` | `/general${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/mood-history${`?${string}` | `#${string}` | ''}` | `/my-quotes${`?${string}` | `#${string}` | ''}` | `/notification-center${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/reminders${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/onboarding/animes${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding/moods${`?${string}` | `#${string}` | ''}` | `/onboarding/name${`?${string}` | `#${string}` | ''}` | `/onboarding/notifications${`?${string}` | `#${string}` | ''}` | `/onboarding/permissions${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/achievements`; params?: Router.UnknownInputParams; } | { pathname: `/create`; params?: Router.UnknownInputParams; } | { pathname: `/debug-notifications`; params?: Router.UnknownInputParams; } | { pathname: `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `/general`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mood-history`; params?: Router.UnknownInputParams; } | { pathname: `/my-quotes`; params?: Router.UnknownInputParams; } | { pathname: `/notification-center`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/reminders`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/animes`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/moods`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/name`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/permissions`; params?: Router.UnknownInputParams; };
    }
  }
}
